name: Continuous Integration (CI);

<<<<<<< HEAD
on:
  pull_request:
    branches: ["main", "dev"]

  push:
    branches: ["main"]
=======
on: [pull_request]
>>>>>>> c88b9c905eb080e7345c20edbd12cbe3ad86988e

jobs:
  install:
    name: Installing Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        run: npm install

<<<<<<< HEAD
  unusedexports:
=======
  unusedexports: 
>>>>>>> c88b9c905eb080e7345c20edbd12cbe3ad86988e
    name: Find unused exports (dead code)
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: run ts-prune
        run: npx ts-prune --error

<<<<<<< HEAD
  testing:
=======
  testing: 
>>>>>>> c88b9c905eb080e7345c20edbd12cbe3ad86988e
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: run tests
        run: npm run test

<<<<<<< HEAD
  lint:
=======
  lint: 
>>>>>>> c88b9c905eb080e7345c20edbd12cbe3ad86988e
    name: Run eslint verification
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: run eslint
        run: npm run lint
